### PR TITLE
Feature/60 update psha adapter v2

### LINKED ISSUE #60: update the psha_adapter
psha_adapter implementation needs finishing now that GMM ard configs are done

- [x] #88
- [x] GMCM #56 
- [x] #90
- [x] add a config to the official models
- [x] change `PshaAdapterInterface.__init__()` args to a  `NshmModel` rather than SRM and GMCM logic trees (we're adapting a model to a hazard engine, so this is more logical)
- [x] `OpenquakeSimplePshaAdapter.write_config() ` writes the job.ini based on the config

### PR DESCRIPTION
**Pull request by chrisdicaprio**
closes #60, #88, #56, #90

### CODE REVIEW

**Comment by chrisdicaprio** [comment]
Questions:
1. should we remove abstract methods `fetch_resources()`, `unpack_resources()`, and `sources_document()` from `PshaAdapterInterface`. They are specific to source model adapters
2. can we get rid of NshmModel.source_logic_tree_nrml()? It's already depricated and not sure the use case. Keeping it trips up mypy if we remove abstract methods from `PshaAdapterInterface` as described above
3. `PshaAdapterInterface.write_config()` has a signature that doesn't quite work for all types of adapters. Particularly,  `OpenquakeConfigPshaAdapter` would work better if `wirte_config()` were given paths to the source and gmcm files. rather than having to re-construct them (I suppose we could use another method to set them). Also, a cache_folder and source_map are really only needed for a source adapter (unless other hazard engines need files for their gmcm lts).
4. If we have setters for `OpenquakeConfigPshaAdapter` to the source and gmcm files, then the linter complains that the base class doesn't have those methods. Could `# type: ignore` or put them in the interface base-class
5. what do we think of the model_args_factory() solution?
6. the warn test still fails in tox env

**Comment by chrisdicaprio** [comment]
Questions:
1. should we remove abstract methods `fetch_resources()`, `unpack_resources()`, and `sources_document()` from `PshaAdapterInterface`. They are specific to source model adapters
2. can we get rid of NshmModel.source_logic_tree_nrml()? It's already depricated and not sure the use case. Keeping it trips up mypy if we remove abstract methods from `PshaAdapterInterface` as described above
3. `PshaAdapterInterface.write_config()` has a signature that doesn't quite work for all types of adapters. Particularly,  `OpenquakeConfigPshaAdapter` would work better if `wirte_config()` were given paths to the source and gmcm files. rather than having to re-construct them (I suppose we could use another method to set them). Also, a cache_folder and source_map are really only needed for a source adapter (unless other hazard engines need files for their gmcm lts).
4. If we have setters for `OpenquakeConfigPshaAdapter` to the source and gmcm files, then the linter complains that the base class doesn't have those methods. Could `# type: ignore` or put them in the interface base-class
5. what do we think of the model_args_factory() solution?
6. the warn test still fails in tox env

**Comment by chrisdicaprio** [comment]
add doc to factory

**Review by chrisbc — APPROVED** [review]
thanks @chrisdicaprio looks good.

**Pull request merged**
